-- Seed: time slots for trainers (next 7 days)
-- Trainer IDs: 1 (Marko), 2 (Amina), 3 (Damir), 4 (Lejla), 5 (Tarik)

INSERT INTO time_slots (trainer_id, start_at, end_at, status) VALUES
-- Marko (id=1) — Strength
(1, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 9 HOUR,  DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 10 HOUR, 'AVAILABLE'),
(1, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 10 HOUR, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 11 HOUR, 'AVAILABLE'),
(1, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 14 HOUR, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 15 HOUR, 'AVAILABLE'),
(1, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 9 HOUR,  DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 10 HOUR, 'AVAILABLE'),
(1, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 11 HOUR, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 12 HOUR, 'AVAILABLE'),

-- Amina (id=2) — Yoga
(2, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 8 HOUR,  DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 9 HOUR, 'AVAILABLE'),
(2, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 17 HOUR, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 18 HOUR, 'AVAILABLE'),
(2, DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 8 HOUR,  DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 9 HOUR, 'AVAILABLE'),
(2, DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 17 HOUR, DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 18 HOUR, 'AVAILABLE'),

-- Damir (id=3) — Cardio
(3, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 7 HOUR,  DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 8 HOUR, 'AVAILABLE'),
(3, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 7 HOUR,  DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 8 HOUR, 'AVAILABLE'),
(3, DATE_ADD(CURDATE(), INTERVAL 4 DAY) + INTERVAL 18 HOUR, DATE_ADD(CURDATE(), INTERVAL 4 DAY) + INTERVAL 19 HOUR, 'AVAILABLE'),

-- Lejla (id=4) — Pilates
(4, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 10 HOUR, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 11 HOUR, 'AVAILABLE'),
(4, DATE_ADD(CURDATE(), INTERVAL 4 DAY) + INTERVAL 10 HOUR, DATE_ADD(CURDATE(), INTERVAL 4 DAY) + INTERVAL 11 HOUR, 'AVAILABLE'),
(4, DATE_ADD(CURDATE(), INTERVAL 5 DAY) + INTERVAL 15 HOUR, DATE_ADD(CURDATE(), INTERVAL 5 DAY) + INTERVAL 16 HOUR, 'AVAILABLE'),

-- Tarik (id=5) — Strength
(5, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 16 HOUR, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 17 HOUR, 'AVAILABLE'),
(5, DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 16 HOUR, DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 17 HOUR, 'AVAILABLE'),
(5, DATE_ADD(CURDATE(), INTERVAL 5 DAY) + INTERVAL 18 HOUR, DATE_ADD(CURDATE(), INTERVAL 5 DAY) + INTERVAL 19 HOUR, 'AVAILABLE');