-- Seed: 30 days of time slots for all trainers
-- Uses INSERT IGNORE so duplicates from V3 are silently skipped (uq_slot_trainer_start)
-- Trainer IDs: 2 (Marko/Strength), 3 (Amina/Yoga), 4 (Damir/Cardio), 5 (Lejla/Pilates), 6 (Tarik/CrossFit)

-- Marko (id=2) — 09:00, 11:00, 15:00
INSERT IGNORE INTO time_slots (trainer_id, start_at, end_at, status)
SELECT 2,
  DATE_ADD(CURDATE(), INTERVAL d.n DAY) + INTERVAL h.h HOUR,
  DATE_ADD(CURDATE(), INTERVAL d.n DAY) + INTERVAL (h.h + 1) HOUR,
  'AVAILABLE'
FROM (
  SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
  UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
  UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
  UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25
  UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
) d
CROSS JOIN (SELECT 9 AS h UNION ALL SELECT 11 UNION ALL SELECT 15) h;

-- Amina (id=3) — 08:00, 10:00, 17:00
INSERT IGNORE INTO time_slots (trainer_id, start_at, end_at, status)
SELECT 3,
  DATE_ADD(CURDATE(), INTERVAL d.n DAY) + INTERVAL h.h HOUR,
  DATE_ADD(CURDATE(), INTERVAL d.n DAY) + INTERVAL (h.h + 1) HOUR,
  'AVAILABLE'
FROM (
  SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
  UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
  UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
  UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25
  UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
) d
CROSS JOIN (SELECT 8 AS h UNION ALL SELECT 10 UNION ALL SELECT 17) h;

-- Damir (id=4) — 07:00, 12:00, 18:00
INSERT IGNORE INTO time_slots (trainer_id, start_at, end_at, status)
SELECT 4,
  DATE_ADD(CURDATE(), INTERVAL d.n DAY) + INTERVAL h.h HOUR,
  DATE_ADD(CURDATE(), INTERVAL d.n DAY) + INTERVAL (h.h + 1) HOUR,
  'AVAILABLE'
FROM (
  SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
  UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
  UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
  UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25
  UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
) d
CROSS JOIN (SELECT 7 AS h UNION ALL SELECT 12 UNION ALL SELECT 18) h;

-- Lejla (id=5) — 09:00, 11:00, 14:00
INSERT IGNORE INTO time_slots (trainer_id, start_at, end_at, status)
SELECT 5,
  DATE_ADD(CURDATE(), INTERVAL d.n DAY) + INTERVAL h.h HOUR,
  DATE_ADD(CURDATE(), INTERVAL d.n DAY) + INTERVAL (h.h + 1) HOUR,
  'AVAILABLE'
FROM (
  SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
  UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
  UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
  UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25
  UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
) d
CROSS JOIN (SELECT 9 AS h UNION ALL SELECT 11 UNION ALL SELECT 14) h;

-- Tarik (id=6) — 10:00, 13:00, 16:00
INSERT IGNORE INTO time_slots (trainer_id, start_at, end_at, status)
SELECT 6,
  DATE_ADD(CURDATE(), INTERVAL d.n DAY) + INTERVAL h.h HOUR,
  DATE_ADD(CURDATE(), INTERVAL d.n DAY) + INTERVAL (h.h + 1) HOUR,
  'AVAILABLE'
FROM (
  SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
  UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
  UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
  UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25
  UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
) d
CROSS JOIN (SELECT 10 AS h UNION ALL SELECT 13 UNION ALL SELECT 16) h;
