-- Seed: time slots for trainers (next 7 days)
-- Trainer IDs assumed: 2 (Marko), 3 (Amina), 4 (Damir), 5 (Lejla), 6 (Tarik)
-- Generates 60-min slots from 09:00 to 18:00 for the next 7 days

INSERT INTO time_slots (trainer_id, start_at, end_at, status) VALUES
-- Marko (id=2) — Strength
(2, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 9 HOUR,  DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 10 HOUR, 'AVAILABLE'),
(2, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 10 HOUR, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 11 HOUR, 'AVAILABLE'),
(2, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 14 HOUR, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 15 HOUR, 'AVAILABLE'),
(2, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 9 HOUR,  DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 10 HOUR, 'AVAILABLE'),
(2, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 11 HOUR, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 12 HOUR, 'AVAILABLE'),

-- Amina (id=3) — Yoga
(3, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 8 HOUR,  DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 9 HOUR, 'AVAILABLE'),
(3, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 17 HOUR, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 18 HOUR, 'AVAILABLE'),
(3, DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 8 HOUR,  DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 9 HOUR, 'AVAILABLE'),
(3, DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 17 HOUR, DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 18 HOUR, 'AVAILABLE'),

-- Damir (id=4) — Cardio
(4, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 7 HOUR,  DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 8 HOUR, 'AVAILABLE'),
(4, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 7 HOUR,  DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 8 HOUR, 'AVAILABLE'),
(4, DATE_ADD(CURDATE(), INTERVAL 4 DAY) + INTERVAL 18 HOUR, DATE_ADD(CURDATE(), INTERVAL 4 DAY) + INTERVAL 19 HOUR, 'AVAILABLE'),

-- Lejla (id=5) — Pilates
(5, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 10 HOUR, DATE_ADD(CURDATE(), INTERVAL 2 DAY) + INTERVAL 11 HOUR, 'AVAILABLE'),
(5, DATE_ADD(CURDATE(), INTERVAL 4 DAY) + INTERVAL 10 HOUR, DATE_ADD(CURDATE(), INTERVAL 4 DAY) + INTERVAL 11 HOUR, 'AVAILABLE'),
(5, DATE_ADD(CURDATE(), INTERVAL 5 DAY) + INTERVAL 15 HOUR, DATE_ADD(CURDATE(), INTERVAL 5 DAY) + INTERVAL 16 HOUR, 'AVAILABLE'),

-- Tarik (id=6) — Strength
(6, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 16 HOUR, DATE_ADD(CURDATE(), INTERVAL 1 DAY) + INTERVAL 17 HOUR, 'AVAILABLE'),
(6, DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 16 HOUR, DATE_ADD(CURDATE(), INTERVAL 3 DAY) + INTERVAL 17 HOUR, 'AVAILABLE'),
(6, DATE_ADD(CURDATE(), INTERVAL 5 DAY) + INTERVAL 18 HOUR, DATE_ADD(CURDATE(), INTERVAL 5 DAY) + INTERVAL 19 HOUR, 'AVAILABLE');